version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ticket-db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tickets.com
      PGADMIN_DEFAULT_PASSWORD: ticketAdmin123
    ports:
      - "5050:80"

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ticket-db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
