version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ticket-db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    networks:
      - tickets_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tickets.com
      PGADMIN_DEFAULT_PASSWORD: ticketAdmin123
    ports:
      - "5050:80"
    networks:
      - tickets_network

  nest:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - tickets_network

networks:
  tickets_network:
    driver: bridge

volumes:
  postgres_data:
